#!/usr/bin/env bash
# display information about subdomains

if [ $# -eq 1 ];
then
  sub=( www lb-01 web-01 web-02)
  for val in "${sub[@]}"
  do
    rec="$(dig "$val"."$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $4 }')"
    add="$(dig "$val"."$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $5 }')"
    printf "The subdomain %s is a %s record and points to %s\n" "$val" "$rec" "$add"
  done
elif [ $# -eq 2 ];
then
  rec="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $4 }')"
  add="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $5 }')"
  printf "The subdomain %s is a %s record and points to %s\n" "$2" "$rec" "$add"
fi
