#!/usr/bin/env bash
# install nginx web server, configure redirect
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw default allow
sudo ufw allow 'Nginx HTTP'
echo y | sudo ufw enable
sudo sh -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
sudo service nginx restart
sudo mkdir /var/www/html/redirect_me
redirect="rewrite ^/redirect_me/$ https://youtu.be/fC7oUOUEEi4 permanent;"
sudo sed -i "/listen \[::\]\:80 default_server\;/a $redirect" /etc/nginx/sites-enabled/default
sudo service nginx reload
