#!/usr/bin/env bash
#displays holberton school 10 times with while, diff messgae on 4 and 8#
i=0
while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 7 ]
	then
		echo "good luck"
	else
		echo 'Holberton School'
	fi
	i=$((i+1))
done
