#!/usr/bin/env bash
# makes nginx use nginx as user
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
